### ISSUE TITLE
Add cauda equinea label to make lumbar registration more user-friendly

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/PAM50#26]
As part of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3599 and https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4180, we have two good forum posts demonstrating how to perform lumbar registration with a new custom label.

In both cases, we asked the users to manually label a location on the PAM50 template representing the cauda equinea:

- In [the first case](https://forum.spinalcordmri.org/t/labels-for-lumbar-spinal-level/737/8?u=joshuacwnewton), @jcohenadad labeled coordinate `[70,69,46]`. 
- In [the second case](https://forum.spinalcordmri.org/t/registration-of-lumbar-data-to-pam50/1109), the user took the initiative to change the coordinate to `[70,70,40]`.
    - The 1-voxel Y coordinate change is left unexplained, but I think was done to line up with the x-y coordinates of the other labels.
    - The 6-voxel Z coordinate change was done to overlap with the last slice of the cord segmentation, recently extended in PR [#21](https://github.com/spinalcordtoolbox/PAM50/pull/21)
      ![image](https://github.com/spinalcordtoolbox/PAM50/assets/16181459/52b67981-5853-4072-94de-d3a688e29c3d)
      > ((Note: If you notice in the image above, the PAM50 cauda equinea label added by the user (light blue) is _right next_ to label 21 i.e. the L1-L2 disc label (dark blue).))

Some questions:

- What coordinate should we use for this label?
   1. The origin label `[70,69,46]`.
   2. The adjusted label `[70,70,40]`.
   3. Re-use label 21 `[70,70,39]`.
      - Note: If we decide to re-use label 21, we will perhaps need to extend the segmentation by 1 slice, as the label exists outside of the segmentation, potentially causing issue [spinalcordtoolbox#3873](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3873). Would doing result in a less accurate segmentation, though? I presume it's probably best to keep two separate labels, even if they are nearly identical location-wise.
- What value should we use for this label?
   - In the forum posts, a value of `99` is used for the cauda equinea label. However, this label is (kind of) reserved for the dummy label used in `sct_register_to_template`, plus this value doesn't really fit with the existing label conventions (1-25, 49, 50).
   - So, perhaps we should use something like `30` or `40`? (This would follow the example given by the PMJ-related labels 50/49, while also giving plenty of room above and below for future labels, since the L5-S1 disc [uses label `25`](https://spinalcordtoolbox.com/user_section/tutorials/registration-to-template/vertebral-labeling/labeling-conventions.html).)

**Comment by jcohenadad** [comment]
Thank you for these excellent questions @joshuacwnewton 

> What coordinate should we use for this label?
The origin label [70,69,46].

I think this is fine. 

> The adjusted label [70,70,40].

I think this is also fine. Probably better in fact, because as you pointed out the new cord seg should now be available in PAM50 (or will be at the time of the course)

> Re-use label 21 [70,70,39]

I would not do that, as it might create confusing with the existing label, users will forget to put it back afterwards, etc. I can see a lot of issues that would be hard for us to debug remotely

> What value should we use for this label?
> In the forum posts, a value of 99 is used for the cauda equinea label. However, this label is (kind of) reserved for the dummy label used in sct_register_to_template, plus this value doesn't really fit with the existing label conventions (1-25, 49, 50).

Yeah I agree. How about we go with `90+`. Like 90, 91, 92, etc.

> So, perhaps we should use something like 30 or 40? (This would follow the example given by the PMJ-related labels 50/49, while also giving plenty of room above and below for future labels, since the L5-S1 disc [uses label 25](https://spinalcordtoolbox.com/user_section/tutorials/registration-to-template/vertebral-labeling/labeling-conventions.html).)

I'd rather keep the 1-->70ish for us. Putting custom values "in between" might create confusion.

**Comment by joshuacwnewton** [comment]
> Yeah I agree. How about we go with 90+. Like 90, 91, 92, etc.

I'm very okay with this. :)

> I'd rather keep the 1-->70ish for us.

Just to clarify, though, what do you mean by "for us"? 

In other words, I'm curious how the cauda equinea label is any different from, e.g. the PMJ label (`50`). (Is there a specific rationale for why the value `50` was acceptable for PMJ, but why 1-70 is unacceptable for the cauda equinea?)

**Comment by jcohenadad** [comment]
@joshuacwnewton I'm very sorry but I misunderstood what was the intention of this issue and related PR-- I thought the plan was _only_ to create a tutorial where we show how to make custom labels (hence the suggestion of `90+` values), but in fact the proposal is to modify the "official" labels by adding one. Hence this falls into the category of "our labels" (that's what I meant here https://github.com/spinalcordtoolbox/PAM50/issues/26#issuecomment-1744968880), and therefore I would use another value than `90` (reserving 90+ for users who would like to create _new_ labels). 

Your solution (ie: modify _our_ `PAM50_label_disc.nii.gz`) is in fact a better solution, because it prevents the dirty hack of asking users to modify source PAM50 files. But in this case, I would propose to use another value, like `60` maybe?

**Comment by joshuacwnewton** [comment]
> But in this case, I would propose to use another value, like 60 maybe?

Exactly my thinking! I'll update the PR to use this value instead.
